# This is a basic workflow to help you get started with Actions

name: Android Pull Request CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: set up Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean the project
        run: ./gradlew clean
        
      - name: Test the project
        run: ./gradlew testAll --no-build-cache

  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean the project
        run: ./gradlew clean

      - name: Run detekt
        run: ./gradlew detekt --no-build-cache
